# numpy revision session

In [1]:
import numpy as np

In [ ]:
# numpy is module
# np is alias
# we can replace np with any name but np is the convention
# numpy stands for numerical python
# used for calculations

In [3]:
# create an array
a = np.array([1,2,3,4,5])
print(a, type(a), a.ndim)

[1 2 3 4 5] <class 'numpy.ndarray'> 1


Note: array is not a list

In [5]:
# array supports indexing and slicing
# first element always begins from zeroth index
# last element is at -1 index

a[0], a[1], a[-1]

(1, 2, 5)

In [6]:
# finds the length
len(a)

5

In [7]:
print(a)

[1 2 3 4 5]


In [8]:
for i in a:
    print(i)

1
2
3
4
5


In [9]:
for i in range(len(a)):
    print(f"value at index {i} is {a[i]}")

value at index 0 is 1
value at index 1 is 2
value at index 2 is 3
value at index 3 is 4
value at index 4 is 5


In [13]:
x = np.arange(1,21)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [14]:
# Note:
#     arange ra range ko kaam ustai ho
#     arange is arange not arrange

In [15]:
x = np.arange(1,31).reshape(3,10)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

note: x in this case is **not 3D array** it is a **2D Array**

In [17]:
a = np.arange(1,31)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]


In [22]:
x = np.split(a,3)
x

[array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30])]

In [23]:
x[0]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])