# Week 4 Workshop

In [2]:
import numpy as np

In [4]:
a = np.array([1,2,3,4,5])
b = np.array([5,4,3,2,1])

In [5]:
print(a+b)

[6 6 6 6 6]


In [8]:
a = np.array(([1,2,4],[3,2,1]))

In [9]:
print(a*2)

[[2 4 8]
 [6 4 2]]


In [11]:
a = np.identity(3, dtype = int)
print(a)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [27]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18])
a = a.reshape(3,3,2)
print(a)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]


In [18]:
a = np.array([1.1,2,3,4,5], dtype = int)
a

array([1, 2, 3, 4, 5])

In [23]:
a = np.full((6,6),6)
print(a)

[[6 6 6 6 6 6]
 [6 6 6 6 6 6]
 [6 6 6 6 6 6]
 [6 6 6 6 6 6]
 [6 6 6 6 6 6]
 [6 6 6 6 6 6]]


In [38]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
odd_numbers = (a%2==1)
a[odd_numbers] = -1
print(a)
print(odd_numbers)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[False  True False  True False  True False  True False  True]


In [51]:
a = np.array([1,2,3,4,5])
b = np.array([1,2,3,0,5])
print(np.intersect1d(a,b))
print(np.where(a==b))
print(np.where(a!=b))

[1 2 3 5]
(array([0, 1, 2, 4], dtype=int64),)
(array([3], dtype=int64),)


In [53]:
b[0], b[1] = b[1], b[0]

In [54]:
print(b)

[2 1 3 0 5]


In [56]:
print(a)
print(b)
np.where(a==b)


[1 2 3 4 5]
[2 1 3 0 5]


(array([2, 4], dtype=int64),)

In [57]:
print(a)
print(b)
np.where(a[:,None]==b)

[1 2 3 4 5]
[2 1 3 0 5]


(array([0, 1, 2, 4], dtype=int64), array([1, 0, 2, 4], dtype=int64))